spring.application.name=spotifyAPI

spring.datasource.url=jdbc:postgresql://mini-spotify-db-murilozg.d.aivencloud.com:24581/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080